thack/api/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import User
from views import ApiSample, EventsApi, EventFares, CountryViewSet, CityViewSet, \
    AirportViewSet, ArtistViewSet, ShowViewSet
from rest_framework import routers
from django.contrib.auth.decorators import login_required, permission_required

router = routers.DefaultRouter()
router.register(r'sample', ApiSample, base_name='sample')
router.register(r'country', CountryViewSet)
router.register(r'city', CityViewSet)
router.register(r'airport', AirportViewSet)
router.register(r'artist', ArtistViewSet)
router.register(r'show', ShowViewSet, base_name='show')

urlpatterns = [
    url(r'sample', login_required(ApiSample.as_view())),
    url(r'events', login_required(EventsApi.as_view())),
    url(r'eventFares', login_required(EventFares.as_view())),

    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

thack/homepage/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required
import views

urlpatterns = [
    url(r'^$', login_required(views.HomeView.as_view())),
    url(r'^logout/$', 'homepage.views.logout_view', name='logout'),
    url(r'^home', login_required(views.HomeView.as_view())),
    url(r'^eventDetail', login_required(views.EventDetailView.as_view())),
    url(r'^profile', views.ProfileView.as_view(), name='profile'),
    url(r'^index', views.IndexView.as_view()),
]

thack/thack/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('api.urls', namespace='api')),
    url('', include('homepage.urls', namespace='content')),
]

thack/api/models.py
from django.db import models

class Country(models.Model):
    name = models.CharField(max_length=100)
    destination = models.BooleanField(default=False)
    origin = models.BooleanField(default=False)
    iata = models.CharField(max_length=10)

    def __unicode__(self):
        return self.name

    class Meta(object):
        verbose_name_plural = u'Countries'


class City(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country, related_name='cities')
    iata = models.CharField(max_length=10)

    def __unicode__(self):
        return self.name

    class Meta(object):
        verbose_name_plural = u'Cities'


class Airport(models.Model):
    name = models.CharField(max_length=200)
    city = models.ForeignKey(City)
    iata = models.CharField(max_length=10)

    def __unicode__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(max_length=200)
    related = models.ManyToManyField('self')

    def __unicode__(self):
        return self.name


class Artist(models.Model):
    name = models.CharField(max_length=100)
    spotify_id = models.CharField(max_length=60)
    genres = models.ManyToManyField(Genre)
    popularity = models.IntegerField(default=0)
    image = models.URLField(blank=True, null=True)

    def __unicode__(self):
        return self.name


class Show(models.Model):
    artists = models.ManyToManyField(Artist)
    city = models.ForeignKey(City)
    datetime = models.DateTimeField()
    lat = models.CharField(max_length=20)
    lon = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='shows', null=True, blank=True)
    description = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return u"{} at {} in {}".format(
            self.artists.first(),
            self.city,
            self.datetime.strftime('%B')
        )

thack/homepage/models.py
from django.db import models

# Create your models here.

thack/api/views.py
import json, spotipy, datetime
from django.http import HttpResponse
from django.views.generic import View
from rest_framework import viewsets
from rest_framework import generics
from django.conf import settings
from models import Country, City, Airport, Artist, Show
from sabreapi import Sabre
from serializers import CountrySerializer, CitySerializer, AirportSerializer, \
    ArtistSerializer, ShowSerializer

class ApiSample(View):
    def get(self, request):
        return HttpResponse(json.dumps(request.GET), content_type='application/json')


class EventsApi(View):
    def get(self, request):
        social_user = request.user.social_auth.get(provider='spotify')
        spotipy_api = spotipy.spotify(auth=social_user.access_token)
        
        artists = self.find_artists(spotipy_api);
        events = self.find_events(artists)

        return HttpResponse(self.event_to_json(events), content_type='application/json')

    def find_artists(self, spotipy_api):
        followed = spotipy_api.current_user_followed_artists();
        ids = [artist['id'] for artist in followed['artists']['items']]
        return Artist.objects.filter(spotify_id__in=ids)

    def find_events(self, artists):
        return Show.objects.filter(artists__in=artists)

    def event_to_json(self, events):
        events = [{"name": e.venue} for e in events]
        return json.dumps({'events': events})


class EventFares(View):
    def get(self, request):
        event = Show.objects.get(id=request.GET['event_id'])
        sabre = Sabre(settings.SABRE_KEY, settings.SABRE_SECRET)
        fares = sabre.api.v1.historical.flights.fares(
            origin=request.GET['origin'],
            destination=request.GET['destination'],
            earliestdeparturedate=(event.datetime - datetime.timedelta(days=6)).isoformat()[:10],
            latestdeparturedate=event.datetime.isoformat()[:10],
            lengthofstay=7
        )
        return HttpResponse(json.dumps(fares), content_type='application/json')


class CountryViewSet(viewsets.ModelViewSet):
    queryset = Country.objects.all()
    serializer_class = CountrySerializer


class CityViewSet(viewsets.ModelViewSet):
    queryset = City.objects.all()
    serializer_class = CitySerializer


class AirportViewSet(viewsets.ModelViewSet):
    queryset = Airport.objects.all()
    serializer_class = AirportSerializer


class ArtistViewSet(viewsets.ModelViewSet):
    queryset = Artist.objects.all()
    serializer_class = ArtistSerializer


class ShowViewSet(viewsets.ModelViewSet):
    serializer_class = ShowSerializer

    def get_queryset(self):
        social_user = self.request.user.social_auth.get(provider='spotify')
        spotipy_api = spotipy.Spotify(auth=social_user.access_token)
        followed = spotipy_api.current_user_followed_artists()
        ids = [artist['id'] for artist in followed['artists']['items']]
        return Show.objects.filter(artists__spotify_id__in=ids)

thack/homepage/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth import logout


class IndexView(TemplateView):
    template_name = 'index.html'


class HomeView(TemplateView):
    template_name = 'home.html'


class ProfileView(TemplateView):
    template_name = 'profile.html'

class EventDetailView(TemplateView):

    template_name = 'event_detail.html'

    def get_context_data(self, **kwargs):
        d = super(EventDetailView, self).get_context_data(**kwargs)
        d['event_id'] = self.request.GET['event_id']
        return d

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

thack/homepage/templates/base.html
{% load static %}
{% load spotify %}
{% with user|spotify as spotify %}
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
	<meta charset="utf-8"/>
	<title>{% block title %}{% endblock %} :: TripMusic</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1" name="viewport"/>
	<meta content="" name="description"/>
	<meta content="" name="author"/>
	<!-- BEGIN GLOBAL MANDATORY STYLES -->

	<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
	<link href="{% static 'assets/global/plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css"/>
	<link href="{% static 'assets/global/plugins/simple-line-icons/simple-line-icons.min.css' %}" rel="stylesheet" type="text/css"/>
	<link href="{% static 'assets/global/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
	<link href="{% static 'assets/global/plugins/uniform/css/uniform.default.css' %}" rel="stylesheet" type="text/css"/>
	<link href="{% static 'assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css' %}" rel="stylesheet" type="text/css"/>
	<!-- END GLOBAL MANDATORY STYLES -->
	<!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
	<link href="{% static 'assets/global/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css' %}" rel="stylesheet" type="text/css"/>
	<link href="{% static 'assets/global/plugins/fullcalendar/fullcalendar.min.css' %}" rel="stylesheet" type="text/css"/>
	<link href="{% static 'assets/global/plugins/jqvmap/jqvmap/jqvmap.css' %}" rel="stylesheet" type="text/css"/>
	<link href="{% static 'assets/global/plugins/morris/morris.css' %}" rel="stylesheet" type="text/css">
	<!-- END PAGE LEVEL PLUGIN STYLES -->
	<!-- BEGIN PAGE STYLES -->
	<link href="{% static 'assets/admin/pages/css/tasks.css' %}" rel="stylesheet" type="text/css"/>
	<!-- END PAGE STYLES -->
	<!-- BEGIN THEME STYLES -->
	<!-- DOC: To use 'rounded corners' style just load 'components-rounded.css' stylesheet instead of 'components.css' in the below style tag -->
	<link href="{% static 'assets/global/css/components-rounded.css" id="style_components' %}" rel="stylesheet" type="text/css"/>
	<link href="{% static 'assets/global/css/plugins.css' %}" rel="stylesheet" type="text/css"/>
	<link href="{% static 'assets/admin/layout/css/layout.css' %}" rel="stylesheet" type="text/css"/>
	<link href="{% static 'assets/admin/layout/css/themes/light.css' %}" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="{% static 'assets/admin/layout/css/custom.css' %}" rel="stylesheet" type="text/css"/>

	<!-- END THEME STYLES -->
	<link rel="shortcut icon" href="favicon.ico"/>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed page-sidebar-closed-hide-logo page-sidebar-closed-hide-logo">
	<!-- BEGIN HEADER -->
	<div class="page-header navbar navbar-fixed-top">
		<!-- BEGIN HEADER INNER -->
		<div class="page-header-inner">
			<!-- BEGIN LOGO -->
			<div class="page-logo">
				<a href="home">
				<img src="{% static 'assets/admin/layout/img/logo-light.png' %}" alt="logo" class="logo-default"/>
				</a>
				<div class="menu-toggler sidebar-toggler">
					<!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
				</div>
			</div>
			<!-- END LOGO -->
			<!-- BEGIN RESPONSIVE MENU TOGGLER -->
			<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
			</a>
			<!-- END RESPONSIVE MENU TOGGLER -->
			<!-- BEGIN PAGE TOP -->
			<div class="page-top">
				<!-- BEGIN TOP NAVIGATION MENU -->
				<div class="top-menu">
					<ul class="nav navbar-nav pull-right">
						<li class="separator hide">
						</li>
						<!-- BEGIN USER LOGIN DROPDOWN -->
						<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
						<li class="dropdown dropdown-user dropdown-dark">
							<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
								<span class="username username-hide-on-mobile">
									{{ spotify.me.display_name }}
								</span>
								<img alt="" class="img-circle" src="{{ spotify.me.images.0.url}}"/>
							</a>
							<ul class="dropdown-menu dropdown-menu-default">
								<li>
									<a href="profile">
									<i class="icon-user"></i> Meu perfil </a>
								</li>
								<li class="divider">
								</li>
								<li>
									<a href="{% url 'content:logout' %}">
									<i class="icon-key"></i> Log Out </a>
								</li>
							</ul>
						</li>
						<!-- END USER LOGIN DROPDOWN -->
					</ul>
				</div>
				<!-- END TOP NAVIGATION MENU -->
			</div>
			<!-- END PAGE TOP -->
		</div>
		<!-- END HEADER INNER -->
	</div>
	<!-- END HEADER -->
	<div class="clearfix">
	</div>
	<!-- BEGIN CONTAINER -->
	<div class="page-container">
		<!-- BEGIN SIDEBAR -->
		<div class="page-sidebar-wrapper">
			<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
			<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
			<div class="page-sidebar navbar-collapse collapse">
				<!-- BEGIN SIDEBAR MENU -->
				<!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
				<!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
				<!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
				<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
				<!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
				<!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
				<ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
					<li class="start active ">
						<a href="home">
						<i class="icon-home"></i>
						<span class="title">Dashboard</span>
						</a>
					</li>
				</ul>
				<!-- END SIDEBAR MENU -->
			</div>
		</div>
		<!-- END SIDEBAR -->
		<!-- BEGIN CONTENT -->
		<div class="page-content-wrapper">
			<div class="page-content">
				<!-- BEGIN PAGE HEAD -->
				<div class="page-head">
					<!-- BEGIN PAGE TITLE -->
					<div class="page-title">
						<h1>{% block description %}{% endblock %}</h1>
					</div>
					<!-- END PAGE TITLE -->
				</div>
				<!-- END PAGE HEAD -->
				<!-- BEGIN PAGE BREADCRUMB -->
				<ul class="page-breadcrumb breadcrumb hide">
					<li>
						<a href="javascript:;">Home</a><i class="fa fa-circle"></i>
					</li>
					<li class="active">
						 Dashboard
					</li>
				</ul>
				<!-- END PAGE BREADCRUMB -->
				<!-- BEGIN PAGE CONTENT INNER -->
				{% block content %}{% endblock %}
				<!-- END PAGE CONTENT INNER -->

				<!-- Modal -->
				<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				    <div class="modal-dialog">
				        <div class="modal-content">
				            <div class="modal-header">
				                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				                 <h4 class="modal-title">Modal title</h4>

				            </div>
				            <div class="modal-body"><div class="te"></div></div>
				            <div class="modal-footer">
				                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				                <button type="button" class="btn btn-primary">Save changes</button>
				            </div>
				        </div>
				        <!-- /.modal-content -->
				    </div>
				    <!-- /.modal-dialog -->
				</div>
				<!-- /.modal -->
			</div>
		</div>
		<!-- END CONTENT -->

	</div>
	<!-- END CONTAINER -->
	<!-- BEGIN FOOTER -->
	<div class="page-footer">
		<div class="page-footer-inner">
			2014 &copy; Katana Inc.
		</div>
		<div class="scroll-to-top">
			<i class="icon-arrow-up"></i>
		</div>
	</div>
	<!-- END FOOTER -->
	<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
	<!-- BEGIN CORE PLUGINS -->
	<!--[if lt IE 9]>
		<script src="{% static 'assets/global/plugins/respond.min.js"></script>
		<script src="{% static 'assets/global/plugins/excanvas.min.js"></script> 
	<![endif]-->
	<script src="{% static 'assets/global/plugins/jquery.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/jquery-migrate.min.js' %}" type="text/javascript"></script>
	<!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
	<script src="{% static 'assets/global/plugins/jquery-ui/jquery-ui.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/jquery.blockui.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/jquery.cokie.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/uniform/jquery.uniform.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js' %}" type="text/javascript"></script>
	<!-- END CORE PLUGINS -->
	<!-- BEGIN PAGE LEVEL PLUGINS -->
	<script src="{% static 'assets/global/plugins/jqvmap/jqvmap/jquery.vmap.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js' %}" type="text/javascript"></script>
	<!-- IMPORTANT! fullcalendar depends on jquery-ui.min.js for drag & drop support -->
	<script src="{% static 'assets/global/plugins/morris/morris.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/morris/raphael-min.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/global/plugins/jquery.sparkline.min.js' %}" type="text/javascript"></script>
	<!-- END PAGE LEVEL PLUGINS -->
	<!-- BEGIN PAGE LEVEL SCRIPTS -->
	<script src="{% static 'assets/global/scripts/metronic.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/admin/layout/scripts/layout.js' %}" type="text/javascript"></script>


	<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.10.1/lodash.min.js" type="text/javascript"></script>
	
	
	<!-- END PAGE LEVEL SCRIPTS -->

	{% block javascript %}{% endblock %}
	<script>
	jQuery(document).ready(function() {    
		Metronic.init(); // init metronic core componets
		Layout.init(); // init layout
	});
	</script>
	<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>
{% endwith %}

thack/homepage/templates/event_detail.html
{% load static %}
{% load spotify %}


<input type="hidden" name="event_id" id="event_id" value="{{ event_id }}"> 

<div id="modal-travel" style="display: none">
	<div class="modal-header">
	    <h3 id="header-detail-event" class="modal-title" style="text-align: center;"></h3>
		<h4 id="header-detail-event-sub" class="modal-title" style="text-align: center;"></h4>
	</div>

	<div id="body-detail-event" class="modal-body">
		<div id="artist">
			
		</div>
		<br><br>
		<div id="modal-travel-price" style="display: none">
			<div id="fare" style="text-align: center;width: 400px;margin: 0 auto;position: relative;">
				<span style=" position: relative; top: -70px; right: -45px;">Ida</span>
				<div id="ida" style="width: 70px;height: 75px;border-color: black;margin-right: 20px;border-style: solid;text-align: center;display: inline;display: inline-block;">
					<span id="ida-dia" style="font-size: 36px;"></span>
					<span id="ida-mes"></span>
				</div>

				<span style=" position: relative; top: -70px; right: -54px;">Volta</span>
			  	<div id="volta" style="width: 70px;height: 75px;border-color: black;margin-right: 20px;border-style: solid;text-align: center;display: inline;display: inline-block;">
					<span id="volta-dia" style="font-size: 36px;"></span>
					<span id="volta-mes"></span>
				</div>
			</div>
			<br>
			<div id="price" style="text-align: center;width: 400px;margin: 0 auto;color: green;">
				<span>$</span>
				<span id="price-text" style="font-size: 40px;"></span>
				<br><br>
				<a href="#" class="btn btn-lg btn-success">Reservar Online</a>
			</div>
		</div>
	</div>
<div>
<input type="hidden" name="event_id" id="event_id" value="1208"> 

<script>
	jQuery(document).ready(function() {
		$.getJSON( "api/show/" + $("#event_id").val(), function( data ) {
			$("#header-detail-event").text(data.name);
			$("#header-detail-event-sub").text($.datepicker.formatDate('dd/mm/yy', new Date(data.datetime)));

			$.getJSON( 'api/eventFares?origin=SFO&destination=LAX&event_id=' + $("#event_id").val(), function( data ) {
				fareData = _.sortBy(data.FareData, 'MinimumFare')[0];

				$("#price-text").text(fareData.MinimumFare);

				$("#ida-dia").text(new Date(fareData.DepartureDateTime).toDateString().split(' ')[2]);
				$("#volta-dia").text(new Date(fareData.ReturnDateTime).toDateString().split(' ')[2]);
				
				$("#ida-mes").text(new Date(fareData.DepartureDateTime).toDateString().split(' ')[1]);
				$("#volta-mes").text(new Date(fareData.ReturnDateTime).toDateString().split(' ')[1]);


				$("#modal-travel-price").show();	
			});

			$("#modal-travel").show();
		});
	});
</script>

thack/homepage/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Home Page{% endblock %}
{% block description %}Eventos{% endblock %}

{% block javascript %}
	<script src="{% static 'assets/admin/layout/scripts/tripmusic.js' %}" type="text/javascript"></script>
	<script>
		jQuery(document).ready(function() {
			TripMusic.init(); // init layout
		});
	</script>
{% endblock %}

{% block content %}

	<div style="text-align: center;">
		<h1 >Our recommendations</h1>
	</div>

    <div id="tilesBox" class="tiles margin-top-10">
    </div>
    
{% endblock %}

thack/homepage/templates/index.html
{% load static %}
{% load spotify %}

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
	<meta charset="utf-8"/>
	<title>TripMusic</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1" name="viewport"/>
	<meta content="" name="description"/>
	<meta content="" name="author"/>

	<link href="{% static 'assets/site/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>

	<link href="{% static 'assets/site/css/bootstrap-theme.min.css' %}" rel="stylesheet" type="text/css"/>
	<link href="{% static 'assets/site/css/site.css' %}" rel="stylesheet" type="text/css"/>
<body>

	<div class="container">

		<div class="starter-template">
			<h1 class="h1-lg">Viaje para sua Música.</h1>
			<p class="lead">Sugestões de destinos com base nos seus gostos musicais.</p>
		

		    {% if user.is_authenticated %}
		    	{% with user|spotify as spotify %}
		        <div class="container">
		            <h2>{{ spotify.me.display_name }}</h2>
		            <a href="/home" class="btn btn-lg btn-success spotify-btn">Vamos lá</a>
		        </div>
		        {% endwith %}
		    {% else %}
		    	<div class="container">
		            <a href="/login/spotify/" class="btn btn-lg btn-success spotify-btn">Login com Spotify</a>
		        </div>

		    {% endif %}
		</div>
	</div><!-- /.container -->
	
	<script src="{% static 'assets/global/plugins/jquery.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/site/js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>

</html>

thack/homepage/templates/profile.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Perfil{% endblock %}
{% block description %}Perfil{% endblock %}

{% block javascript %}
	<script src="{% static 'assets/admin/layout/scripts/tripmusic.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}

{% endblock %}